// GitHub reducer constants
export const GITHUB_FETCH_DATA_REQUEST = "GITHUB_FETCH_DATA_REQUEST";
export const GITHUB_FETCH_DATA_SUCCESS = "GITHUB_FETCH_DATA_SUCCESS";
export const GITHUB_FETCH_DATA_FAILURE = "GITHUB_FETCH_DATA_FAILURE";