// Netlify reducer constants
export const NETLIFY_FETCH_DATA_REQUEST = "NETLIFY_FETCH_DATA_REQUEST";
export const NETLIFY_FETCH_DATA_SUCCESS = "NETLIFY_FETCH_DATA_SUCCESS";
export const NETLIFY_FETCH_DATA_FAILURE = "NETLIFY_FETCH_DATA_FAILURE";
