// Vercel reducer constants
export const VERCEL_FETCH_DATA_REQUEST = "VERCEL_FETCH_DATA_REQUEST";
export const VERCEL_FETCH_DATA_SUCCESS = "VERCEL_FETCH_DATA_SUCCESS";
export const VERCEL_FETCH_DATA_FAILURE = "VERCEL_FETCH_DATA_FAILURE";
export const VERCEL_COLOR_MODE = "VERCEL_COLOR_MODE";
